# Generated by Django 4.0.10 on 2023-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='range1',
            field=models.IntegerField(verbose_name='Семья'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='range2',
            field=models.IntegerField(verbose_name='Друзья'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='range3',
            field=models.IntegerField(verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='range4',
            field=models.IntegerField(verbose_name='Хобби'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='range5',
            field=models.IntegerField(verbose_name='Финансы'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='range6',
            field=models.IntegerField(verbose_name='Спорт и здоровье'),
        ),
    ]
